rootProject.name = '消息可靠性实验室'
include 'support'
['kafka', 'rocketmq'].each { section ->
    def dir = file(section)
    if (dir.exists()) dir.eachDir { lesson ->
        if (new File(lesson, 'practice').exists()) {
            include "${section}-${lesson.name}"
            project(":${section}-${lesson.name}").projectDir = new File(lesson, 'practice')
        }
    }
}
