server.address=127.0.0.1
server.port=18084
spring.datasource.generate-unique-name=true
spring.sql.init.mode=always
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=5s
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.connection-timeout=1000
