server.address=0.0.0.0
server.port=${LAB_HTTP_PORT:8080}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s
spring.application.name=backend-capstone
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
server.error.include-message=never
server.tomcat.threads.max=32
server.tomcat.accept-count=32
logging.level.org.apache.kafka=WARN
logging.level.com.zaxxer.hikari=WARN
