apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: orders
    automountServiceAccountToken: false
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: observer
    automountServiceAccountToken: false
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: course-observer
    rules:
      - apiGroups: ['']
        resources: [pods, services, events]
        verbs: [get, list]
      - apiGroups: [apps]
        resources: [deployments, replicasets]
        verbs: [get, list]
      - apiGroups: [discovery.k8s.io]
        resources: [endpointslices]
        verbs: [get, list]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: course-observer
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: course-observer
    subjects:
      - kind: ServiceAccount
        name: observer
        namespace: ${NAMESPACE}
