// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: delivery.proto
// Protobuf Java Version: 4.29.0

package labs.capstone.protocol;

public final class DeliveryOuterClass {
  private DeliveryOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      DeliveryOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capstone_v1_OrderEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_capstone_v1_OrderEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capstone_v1_Receipt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_capstone_v1_Receipt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capstone_v1_ProbeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_capstone_v1_ProbeRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016delivery.proto\022\013capstone.v1\"r\n\nOrderEv" +
      "ent\022\020\n\010event_id\030\001 \001(\t\022\022\n\nrequest_id\030\002 \001(" +
      "\t\022\013\n\003sku\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\005\022\017\n\007vers" +
      "ion\030\005 \001(\003\022\016\n\006status\030\006 \001(\t\">\n\007Receipt\022\020\n\010" +
      "event_id\030\001 \001(\t\022\021\n\tduplicate\030\002 \001(\010\022\016\n\006sta" +
      "tus\030\003 \001(\t\"\016\n\014ProbeRequest2|\n\010Delivery\0226\n" +
      "\005Apply\022\027.capstone.v1.OrderEvent\032\024.capsto" +
      "ne.v1.Receipt\0228\n\005Probe\022\031.capstone.v1.Pro" +
      "beRequest\032\024.capstone.v1.ReceiptB\032\n\026labs." +
      "capstone.protocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_capstone_v1_OrderEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_capstone_v1_OrderEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_capstone_v1_OrderEvent_descriptor,
        new java.lang.String[] { "EventId", "RequestId", "Sku", "Quantity", "Version", "Status", });
    internal_static_capstone_v1_Receipt_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_capstone_v1_Receipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_capstone_v1_Receipt_descriptor,
        new java.lang.String[] { "EventId", "Duplicate", "Status", });
    internal_static_capstone_v1_ProbeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_capstone_v1_ProbeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_capstone_v1_ProbeRequest_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
