// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: delivery.proto
// Protobuf Java Version: 4.29.0

package labs.capstone.protocol;

public interface OrderEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capstone.v1.OrderEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string request_id = 2;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 2;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string sku = 3;</code>
   * @return The sku.
   */
  java.lang.String getSku();
  /**
   * <code>string sku = 3;</code>
   * @return The bytes for sku.
   */
  com.google.protobuf.ByteString
      getSkuBytes();

  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>int64 version = 5;</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
