// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: delivery.proto
// Protobuf Java Version: 4.29.0

package labs.capstone.protocol;

public interface ProbeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capstone.v1.ProbeRequest)
    com.google.protobuf.MessageOrBuilder {
}
