// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: delivery.proto
// Protobuf Java Version: 4.29.0

package labs.capstone.protocol;

public interface ReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:capstone.v1.Receipt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>bool duplicate = 2;</code>
   * @return The duplicate.
   */
  boolean getDuplicate();

  /**
   * <code>string status = 3;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
