dependencies {
    implementation project(':common')
    implementation project(':c01-08-query-project-lab')
    implementation 'org.openjdk.jmh:jmh-core:1.37'
    annotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
}
tasks.register('jmh', JavaExec) {
    dependsOn tasks.named('classes')
    classpath=sourceSets.main.runtimeClasspath
    mainClass='org.openjdk.jmh.Main'
    args 'labs.foundation.QueryBenchmark', '-wi', '2', '-i', '3', '-w', '500ms', '-r', '500ms', '-f', '1', '-t', '1', '-rf', 'json', '-rff', layout.buildDirectory.file('jmh-result.json').get().asFile.absolutePath
    maxHeapSize='192m'
}
