// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inventory.proto
// Protobuf Java Version: 4.29.0

package labs.distributed.grpc.protocol;

public final class InventoryOuterClass {
  private InventoryOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      InventoryOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_v1_QuoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_inventory_v1_QuoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_v1_ReserveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_inventory_v1_ReserveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_v1_WatchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_inventory_v1_WatchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_v1_InventoryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_inventory_v1_InventoryReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\022\014inventory.v1\"!\n\014Quote" +
      "Request\022\013\n\003sku\030\001 \001(\tJ\004\010\002\020\003\"<\n\016ReserveReq" +
      "uest\022\013\n\003key\030\001 \001(\t\022\013\n\003sku\030\002 \001(\t\022\020\n\010quanti" +
      "ty\030\003 \001(\005\"\035\n\014WatchRequest\022\r\n\005count\030\001 \001(\005\"" +
      "m\n\016InventoryReply\022\013\n\003sku\030\001 \001(\t\022\021\n\tavaila" +
      "ble\030\002 \001(\005\022\020\n\010trace_id\030\003 \001(\t\022\030\n\020remaining" +
      "_millis\030\004 \001(\003\022\017\n\007payload\030\005 \001(\t2\332\001\n\tInven" +
      "tory\022A\n\005Quote\022\032.inventory.v1.QuoteReques" +
      "t\032\034.inventory.v1.InventoryReply\022E\n\007Reser" +
      "ve\022\034.inventory.v1.ReserveRequest\032\034.inven" +
      "tory.v1.InventoryReply\022C\n\005Watch\022\032.invent" +
      "ory.v1.WatchRequest\032\034.inventory.v1.Inven" +
      "toryReply0\001B\"\n\036labs.distributed.grpc.pro" +
      "tocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_inventory_v1_QuoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_inventory_v1_QuoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_inventory_v1_QuoteRequest_descriptor,
        new java.lang.String[] { "Sku", });
    internal_static_inventory_v1_ReserveRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inventory_v1_ReserveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_inventory_v1_ReserveRequest_descriptor,
        new java.lang.String[] { "Key", "Sku", "Quantity", });
    internal_static_inventory_v1_WatchRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_inventory_v1_WatchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_inventory_v1_WatchRequest_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_inventory_v1_InventoryReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_inventory_v1_InventoryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_inventory_v1_InventoryReply_descriptor,
        new java.lang.String[] { "Sku", "Available", "TraceId", "RemainingMillis", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
