// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inventory.proto
// Protobuf Java Version: 4.29.0

package labs.distributed.grpc.protocol;

public interface InventoryReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.v1.InventoryReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sku = 1;</code>
   * @return The sku.
   */
  java.lang.String getSku();
  /**
   * <code>string sku = 1;</code>
   * @return The bytes for sku.
   */
  com.google.protobuf.ByteString
      getSkuBytes();

  /**
   * <code>int32 available = 2;</code>
   * @return The available.
   */
  int getAvailable();

  /**
   * <code>string trace_id = 3;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string trace_id = 3;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>int64 remaining_millis = 4;</code>
   * @return The remainingMillis.
   */
  long getRemainingMillis();

  /**
   * <code>string payload = 5;</code>
   * @return The payload.
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 5;</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();
}
