// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inventory.proto
// Protobuf Java Version: 4.29.0

package labs.distributed.grpc.protocol;

/**
 * Protobuf type {@code inventory.v1.InventoryReply}
 */
public final class InventoryReply extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:inventory.v1.InventoryReply)
    InventoryReplyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      InventoryReply.class.getName());
  }
  // Use InventoryReply.newBuilder() to construct.
  private InventoryReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InventoryReply() {
    sku_ = "";
    traceId_ = "";
    payload_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return labs.distributed.grpc.protocol.InventoryOuterClass.internal_static_inventory_v1_InventoryReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return labs.distributed.grpc.protocol.InventoryOuterClass.internal_static_inventory_v1_InventoryReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            labs.distributed.grpc.protocol.InventoryReply.class, labs.distributed.grpc.protocol.InventoryReply.Builder.class);
  }

  public static final int SKU_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sku_ = "";
  /**
   * <code>string sku = 1;</code>
   * @return The sku.
   */
  @java.lang.Override
  public java.lang.String getSku() {
    java.lang.Object ref = sku_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sku_ = s;
      return s;
    }
  }
  /**
   * <code>string sku = 1;</code>
   * @return The bytes for sku.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSkuBytes() {
    java.lang.Object ref = sku_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sku_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABLE_FIELD_NUMBER = 2;
  private int available_ = 0;
  /**
   * <code>int32 available = 2;</code>
   * @return The available.
   */
  @java.lang.Override
  public int getAvailable() {
    return available_;
  }

  public static final int TRACE_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceId_ = "";
  /**
   * <code>string trace_id = 3;</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <code>string trace_id = 3;</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMAINING_MILLIS_FIELD_NUMBER = 4;
  private long remainingMillis_ = 0L;
  /**
   * <code>int64 remaining_millis = 4;</code>
   * @return The remainingMillis.
   */
  @java.lang.Override
  public long getRemainingMillis() {
    return remainingMillis_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object payload_ = "";
  /**
   * <code>string payload = 5;</code>
   * @return The payload.
   */
  @java.lang.Override
  public java.lang.String getPayload() {
    java.lang.Object ref = payload_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      payload_ = s;
      return s;
    }
  }
  /**
   * <code>string payload = 5;</code>
   * @return The bytes for payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPayloadBytes() {
    java.lang.Object ref = payload_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      payload_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sku_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sku_);
    }
    if (available_ != 0) {
      output.writeInt32(2, available_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, traceId_);
    }
    if (remainingMillis_ != 0L) {
      output.writeInt64(4, remainingMillis_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payload_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sku_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sku_);
    }
    if (available_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, available_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, traceId_);
    }
    if (remainingMillis_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, remainingMillis_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payload_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof labs.distributed.grpc.protocol.InventoryReply)) {
      return super.equals(obj);
    }
    labs.distributed.grpc.protocol.InventoryReply other = (labs.distributed.grpc.protocol.InventoryReply) obj;

    if (!getSku()
        .equals(other.getSku())) return false;
    if (getAvailable()
        != other.getAvailable()) return false;
    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (getRemainingMillis()
        != other.getRemainingMillis()) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKU_FIELD_NUMBER;
    hash = (53 * hash) + getSku().hashCode();
    hash = (37 * hash) + AVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + getAvailable();
    hash = (37 * hash) + TRACE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (37 * hash) + REMAINING_MILLIS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRemainingMillis());
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static labs.distributed.grpc.protocol.InventoryReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static labs.distributed.grpc.protocol.InventoryReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static labs.distributed.grpc.protocol.InventoryReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(labs.distributed.grpc.protocol.InventoryReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code inventory.v1.InventoryReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:inventory.v1.InventoryReply)
      labs.distributed.grpc.protocol.InventoryReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return labs.distributed.grpc.protocol.InventoryOuterClass.internal_static_inventory_v1_InventoryReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return labs.distributed.grpc.protocol.InventoryOuterClass.internal_static_inventory_v1_InventoryReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              labs.distributed.grpc.protocol.InventoryReply.class, labs.distributed.grpc.protocol.InventoryReply.Builder.class);
    }

    // Construct using labs.distributed.grpc.protocol.InventoryReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sku_ = "";
      available_ = 0;
      traceId_ = "";
      remainingMillis_ = 0L;
      payload_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return labs.distributed.grpc.protocol.InventoryOuterClass.internal_static_inventory_v1_InventoryReply_descriptor;
    }

    @java.lang.Override
    public labs.distributed.grpc.protocol.InventoryReply getDefaultInstanceForType() {
      return labs.distributed.grpc.protocol.InventoryReply.getDefaultInstance();
    }

    @java.lang.Override
    public labs.distributed.grpc.protocol.InventoryReply build() {
      labs.distributed.grpc.protocol.InventoryReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public labs.distributed.grpc.protocol.InventoryReply buildPartial() {
      labs.distributed.grpc.protocol.InventoryReply result = new labs.distributed.grpc.protocol.InventoryReply(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(labs.distributed.grpc.protocol.InventoryReply result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sku_ = sku_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.available_ = available_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.traceId_ = traceId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.remainingMillis_ = remainingMillis_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.payload_ = payload_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof labs.distributed.grpc.protocol.InventoryReply) {
        return mergeFrom((labs.distributed.grpc.protocol.InventoryReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(labs.distributed.grpc.protocol.InventoryReply other) {
      if (other == labs.distributed.grpc.protocol.InventoryReply.getDefaultInstance()) return this;
      if (!other.getSku().isEmpty()) {
        sku_ = other.sku_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAvailable() != 0) {
        setAvailable(other.getAvailable());
      }
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getRemainingMillis() != 0L) {
        setRemainingMillis(other.getRemainingMillis());
      }
      if (!other.getPayload().isEmpty()) {
        payload_ = other.payload_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sku_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              available_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              traceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              remainingMillis_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              payload_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sku_ = "";
    /**
     * <code>string sku = 1;</code>
     * @return The sku.
     */
    public java.lang.String getSku() {
      java.lang.Object ref = sku_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sku_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sku = 1;</code>
     * @return The bytes for sku.
     */
    public com.google.protobuf.ByteString
        getSkuBytes() {
      java.lang.Object ref = sku_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sku_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku = 1;</code>
     * @param value The sku to set.
     * @return This builder for chaining.
     */
    public Builder setSku(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sku_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sku = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSku() {
      sku_ = getDefaultInstance().getSku();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sku = 1;</code>
     * @param value The bytes for sku to set.
     * @return This builder for chaining.
     */
    public Builder setSkuBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sku_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int available_ ;
    /**
     * <code>int32 available = 2;</code>
     * @return The available.
     */
    @java.lang.Override
    public int getAvailable() {
      return available_;
    }
    /**
     * <code>int32 available = 2;</code>
     * @param value The available to set.
     * @return This builder for chaining.
     */
    public Builder setAvailable(int value) {

      available_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 available = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailable() {
      bitField0_ = (bitField0_ & ~0x00000002);
      available_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <code>string trace_id = 3;</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string trace_id = 3;</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string trace_id = 3;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string trace_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      traceId_ = getDefaultInstance().getTraceId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string trace_id = 3;</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long remainingMillis_ ;
    /**
     * <code>int64 remaining_millis = 4;</code>
     * @return The remainingMillis.
     */
    @java.lang.Override
    public long getRemainingMillis() {
      return remainingMillis_;
    }
    /**
     * <code>int64 remaining_millis = 4;</code>
     * @param value The remainingMillis to set.
     * @return This builder for chaining.
     */
    public Builder setRemainingMillis(long value) {

      remainingMillis_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 remaining_millis = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemainingMillis() {
      bitField0_ = (bitField0_ & ~0x00000008);
      remainingMillis_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object payload_ = "";
    /**
     * <code>string payload = 5;</code>
     * @return The payload.
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payload_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string payload = 5;</code>
     * @return The bytes for payload.
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string payload = 5;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      payload_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string payload = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      payload_ = getDefaultInstance().getPayload();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string payload = 5;</code>
     * @param value The bytes for payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      payload_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:inventory.v1.InventoryReply)
  }

  // @@protoc_insertion_point(class_scope:inventory.v1.InventoryReply)
  private static final labs.distributed.grpc.protocol.InventoryReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new labs.distributed.grpc.protocol.InventoryReply();
  }

  public static labs.distributed.grpc.protocol.InventoryReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InventoryReply>
      PARSER = new com.google.protobuf.AbstractParser<InventoryReply>() {
    @java.lang.Override
    public InventoryReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InventoryReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InventoryReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public labs.distributed.grpc.protocol.InventoryReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

