// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inventory.proto
// Protobuf Java Version: 4.29.0

package labs.distributed.grpc.protocol;

public interface QuoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.v1.QuoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sku = 1;</code>
   * @return The sku.
   */
  java.lang.String getSku();
  /**
   * <code>string sku = 1;</code>
   * @return The bytes for sku.
   */
  com.google.protobuf.ByteString
      getSkuBytes();
}
