// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inventory.proto
// Protobuf Java Version: 4.29.0

package labs.distributed.grpc.protocol;

public interface WatchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.v1.WatchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();
}
