"""Synthetic filesystem/helper fixtures only; no IDE, parser, sudo or OS writes."""
import copy
import hashlib
import json
from pathlib import Path
import stat
import struct
import subprocess
import sys
import tempfile
from types import SimpleNamespace
import unittest
from unittest.mock import patch
import zipfile

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import apparmor_profile as profile


XML = (b'<component xmlns="http://jetbrains.org/intellij/schema/application-info">'
       b'<build number="IU-261.27258.48"/>'
       b'<names product="IDEA" fullname="IntelliJ IDEA"/></component>')
NAMES = b'\xca\xfe\xba\xbe\x00\x00\x00\x3d\x00\x02\x01' + struct.pack('>H', len(XML)) + XML
TEMPLATE = (b'# This profile is autogenerated by %s to allow running sandboxed JCEF\n'
            b'abi <abi/4.0>,\ninclude <tunables/global>\n\n'
            b'profile "%s" flags=(unconfined) {\n  userns,\n\n'
            b'  include if exists <local/chrome>\n}\n')
GENERATOR = b'\xca\xfe\xba\xbe\x00\x00\x00\x3d\x00\x02\x01' + struct.pack('>H', len(TEMPLATE)) + TEMPLATE


class Fixture(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.exe = Path('/sdk/idea/bin/idea')
        self.idea = Path('/sdk/idea')
        self.env = {'PATH': '/usr/sbin:/usr/bin', 'LC_ALL': 'C'}
        self.calls = []
        for value in ('/etc/apparmor.d/abi', '/etc/apparmor.d/tunables', '/etc/apparmor.d/local',
                      '/var/cache/apparmor', '/usr/sbin', '/usr/bin'):
            (self.root / value.lstrip('/')).mkdir(parents=True, exist_ok=True)
        self.write(profile.CONFIG, b'# fixture default config\n')
        self.write(profile.INVENTORY, b'other-policy (enforce)\n')
        self.write('/etc/apparmor.d/abi/4.0', b'policy { versions { v8 { yes } } }\n')
        self.write('/etc/apparmor.d/tunables/global', b'# fixture tunables\n')
        self.write('/usr/sbin/apparmor_parser', b'synthetic parser, not executable code', 0o755)
        self.write('/usr/bin/dpkg-query', b'synthetic query, not executable code', 0o755)
        md5 = hashlib.md5(b'synthetic parser, not executable code', usedforsecurity=False).hexdigest()
        self.write('/var/lib/dpkg/info/apparmor.md5sums', f'{md5}  usr/sbin/apparmor_parser\n'.encode())
        pins = {}
        class_hashes = {profile.GENERATOR_CLASS: profile._sha(GENERATOR),
                        profile.NAMES_CLASS: profile._sha(NAMES)}
        for name, member, data in ((profile.GENERATOR_JAR, profile.GENERATOR_CLASS, GENERATOR),
                                   (profile.CORE_JAR, profile.NAMES_CLASS, NAMES)):
            path = self.local(self.idea / name)
            path.parent.mkdir(parents=True, exist_ok=True)
            with zipfile.ZipFile(path, 'w') as archive:
                archive.writestr(member, data)
            raw = path.read_bytes()
            pins[name] = (len(raw), profile._sha(raw))
        for name in ('bin/idea', 'jbr/bin/java'):
            raw = ('synthetic ' + name).encode()
            self.write(self.idea / name, raw, 0o755)
            pins[name] = (len(raw), profile._sha(raw))
        # Simulate root ownership without chown or privilege. Real mode checks
        # remain active; trust's actual owner rejection has separate fixtures.
        original_trust = profile._trust
        original_alias_trust = profile._trust_distro_alias
        def synthetic_root(info, directory=False):
            return original_trust(SimpleNamespace(st_uid=0, st_mode=info.st_mode), directory)
        def synthetic_root_alias(info):
            return original_alias_trust(SimpleNamespace(st_uid=0, st_mode=info.st_mode))
        for target, replacement in (('_trust', synthetic_root), ('PINNED', pins),
                                    ('CLASS_HASHES', class_hashes), ('_trust_distro_alias', synthetic_root_alias)):
            p = patch.object(profile, target, replacement)
            p.start()
            self.addCleanup(p.stop)
        p = patch.object(profile.os, 'geteuid', return_value=0)
        p.start()
        self.addCleanup(p.stop)

    def local(self, value):
        return self.root / str(value).lstrip('/')

    def write(self, value, raw, mode=0o644):
        path = self.local(value)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(raw)
        path.chmod(mode)
        return path

    def runner(self, command, **kwargs):
        self.calls.append((command, kwargs))
        if command[0] == '/usr/bin/dpkg-query':
            output = b'install ok installed\t4.0.1-0ubuntu0.24.04.4\tamd64\n'
        elif command[1:] == ['--version']:
            output = b'AppArmor parser version 4.0.1\nCopyright fixture\n'
        elif command[1:] == ['--print-config-file', '--version']:
            output = b'/etc/apparmor/parser.conf\nAppArmor parser version 4.0.1\nCopyright fixture\n'
        elif command[1:] == ['--print-cache-dir']:
            output = b'/var/cache/apparmor/synthetic-feature\n'
        elif command[1:] == ['-n', '-l']:
            output = b'Matching Defaults entries for fixture:\n    secure_path=/usr/sbin:/usr/bin\nUser may run:\n    (ALL : ALL) NOPASSWD: ALL\n'
        else:
            self.fail('unexpected fixture command')
        return subprocess.CompletedProcess(command, 0, stdout=output)

    def prepare(self, **changes):
        return profile.prepare(self.exe, self.idea, runner=changes.pop('runner', self.runner),
                               env=changes.pop('env', self.env), filesystem_root=self.root, **changes)

    def before(self, candidate, **changes):
        return profile.recheck_before(candidate, self.exe, env=self.env, filesystem_root=self.root, **changes)

    def install_fixture(self, candidate):
        self.write(candidate['destination'], candidate['expected_utf8'].encode())
        self.write(profile.INVENTORY, f'{self.exe} (unconfined)\n'.encode())

    def installed(self, candidate):
        return profile.verify_installed(candidate, env=self.env, filesystem_root=self.root)

    def error(self, code, function, *args, **kwargs):
        with self.assertRaises(profile.ProfileError) as caught:
            function(*args, **kwargs)
        self.assertEqual(caught.exception.code, code)
        self.assertEqual(str(caught.exception), code)
        self.assertIs(type(caught.exception.step), str)
        self.assertIn(caught.exception.step, profile.STEPS)
        return caught.exception


class ProfileFixtureTests(Fixture):
    def test_prepare_recheck_and_installed_exact_vendor_bytes(self):
        candidate = self.prepare()
        self.assertEqual(candidate['destination'], '/etc/apparmor.d/idea-null')
        self.assertIn('profile "/sdk/idea/bin/idea" flags=(unconfined)', candidate['expected_utf8'])
        self.assertTrue(candidate['expected_utf8'].endswith('  include if exists <local/chrome>\n}\n'))
        self.assertEqual(json.loads(json.dumps(candidate)), candidate)
        self.assertEqual(self.before(candidate)['status'], 'PREINSTALL_VERIFIED')
        self.install_fixture(candidate)
        self.assertEqual(self.installed(candidate)['status'], 'INSTALLED_VERIFIED')

    def test_actual_java_or_native_binary_is_selected_by_observed_path(self):
        self.exe = self.idea / 'jbr/bin/java'
        candidate = self.prepare()
        self.assertIn(str(self.exe), candidate['expected_utf8'])
        self.exe = self.idea / 'other/java'
        self.error('EXECUTABLE_MISMATCH', self.prepare)

    def test_unused_destination_does_not_override_loaded_name_collision(self):
        self.write(profile.INVENTORY, f'{self.exe} (complain)\n'.encode())
        self.error('PROFILE_COLLISION', self.prepare)
        self.assertFalse(self.local('/etc/apparmor.d/idea-null').exists())
        self.assertEqual(self.calls, [])

    def test_collision_is_rechecked_immediately_before_action(self):
        candidate = self.prepare()
        self.write(profile.INVENTORY, f'{self.exe} (enforce)\n'.encode())
        self.error('PROFILE_COLLISION', self.before, candidate)

    def test_unrelated_inventory_names_are_discarded_and_prefix_is_not_collision(self):
        self.write(profile.INVENTORY, f'{self.exe}-other (enforce)\nprivate unrelated name (complain)\n'.encode())
        public = json.dumps(profile.public_evidence(self.prepare()))
        self.assertNotIn('private', public)
        self.assertNotIn('other', public)

    def test_unreadable_inventory_is_unknown_not_absence(self):
        original = profile._Observation.read
        def denied(obs, path, **kwargs):
            if path == profile.INVENTORY:
                raise PermissionError('private detail must not escape')
            return original(obs, path, **kwargs)
        with patch.object(profile._Observation, 'read', denied):
            self.error('INVENTORY_UNKNOWN', self.prepare)

    def test_oversized_or_malformed_inventory_is_unknown(self):
        for raw in (b'x' * (profile.TEXT_LIMIT + 1), b'invalid', b'policy (bogus)\n',
                    b'policy (enforce)', b'\xff (enforce)\n', b'name\x00 (enforce)\n', b'\n'):
            with self.subTest(raw=raw[:30]):
                self.write(profile.INVENTORY, raw)
                self.error('INVENTORY_UNKNOWN', self.prepare)

    def test_dangling_destination_and_symlink_ancestor_are_rejected(self):
        destination = self.local('/etc/apparmor.d/idea-null')
        destination.symlink_to('/nonexistent-fixture-only')
        self.error('PATH_UNSAFE', self.prepare)
        destination.unlink()
        directory = self.local('/etc/apparmor.d/tunables')
        directory.rename(directory.with_name('real-tunables'))
        directory.symlink_to('real-tunables', target_is_directory=True)
        self.error('FILE_UNKNOWN', self.prepare)

    def test_candidate_occupancy_change_or_earlier_vacancy_blocks(self):
        self.write('/etc/apparmor.d/idea-null', b'prior existing unrelated file\n')
        candidate = self.prepare()
        self.assertEqual(candidate['candidate_checks'], 2)
        self.local('/etc/apparmor.d/idea-null').unlink()
        self.error('DESTINATION_CHANGED', self.before, candidate)
        self.write('/etc/apparmor.d/idea-null', b'prior existing unrelated file\n')
        self.write(candidate['destination'], b'occupied\n')
        self.error('DESTINATION_CHANGED', self.before, candidate)

    def test_candidate_search_stops_at_vendor_limit(self):
        for i in range(profile.CANDIDATE_LIMIT):
            suffix = f'-{i}' if i else ''
            self.write('/etc/apparmor.d/idea-null' + suffix, b'')
        self.error('BOUNDS_EXCEEDED', self.prepare)

    def test_changed_include_or_optional_presence_blocks_recheck(self):
        candidate = self.prepare()
        self.write('/etc/apparmor.d/tunables/global', b'# changed\n')
        self.error('FILE_CHANGED', self.before, candidate)
        candidate = self.prepare()
        self.write('/etc/apparmor.d/local/chrome', b'# previously absent\n')
        self.error('FILE_CHANGED', self.before, candidate)

    def test_unknown_recursive_directory_or_alternate_include_blocks(self):
        for raw in (b'include <unknown/entry>\n', b'include <tunables/global>\n',
                    b'include <tunables/home.d>\n', b'include "tunables/home"\n',
                    b'include \\\n <tunables/home>\n', b'alias /sdk/ -> /other/,\n'):
            with self.subTest(raw=raw):
                self.write('/etc/apparmor.d/tunables/global', raw)
                self.error('INCLUDE_UNKNOWN', self.prepare)
        self.write('/etc/apparmor.d/tunables/global', b'include <tunables/home>\n')
        self.local('/etc/apparmor.d/tunables/home').mkdir()
        self.error('INCLUDE_UNKNOWN', self.prepare)

    def test_known_nested_include_is_closed_and_changed_nested_content_fails(self):
        self.write('/etc/apparmor.d/tunables/global', b'#include <tunables/proc>\n')
        self.write('/etc/apparmor.d/tunables/proc', b'@{PROC}=/proc/\n')
        candidate = self.prepare()
        self.before(candidate)
        self.write('/etc/apparmor.d/tunables/proc', b'@{PROC}=/different/\n')
        self.error('FILE_CHANGED', self.before, candidate)

    def test_unreviewed_local_policy_is_not_certified_by_a_hash(self):
        self.write('/etc/apparmor.d/local/chrome', b'profile /other flags=(unconfined) { userns, }\n')
        self.error('INCLUDE_UNKNOWN', self.prepare)

    def test_file_and_total_and_file_count_bounds_remain_fixed(self):
        self.write('/etc/apparmor.d/tunables/global', b'#' + b'a' * profile.TEXT_LIMIT)
        self.error('BOUNDS_EXCEEDED', self.prepare)
        self.write('/etc/apparmor.d/tunables/global', b''.join(
            f'include <tunables/{name}>\n'.encode() for name in ('home', 'multiarch', 'proc', 'alias', 'kernelvars', 'share')))
        for name in ('home', 'multiarch', 'proc', 'alias', 'kernelvars', 'share'):
            self.write('/etc/apparmor.d/tunables/' + name, b'# fixture\n')
        self.error('BOUNDS_EXCEEDED', self.prepare)
        obs = profile._Observation(self.root)
        for i in range(5):
            self.write(f'/etc/chunk{i}', b'#' * profile.TEXT_LIMIT)
        for i in range(4):
            obs.read(Path(f'/etc/chunk{i}'), effective=True)
        self.error('BOUNDS_EXCEEDED', obs.read, Path('/etc/chunk4'), effective=True)

    def test_deadline_is_not_extended_by_helper_calls(self):
        with patch.object(profile.time, 'monotonic', side_effect=[0, 6]):
            self.error('BOUNDS_EXCEEDED', self.prepare)

    def test_changed_executable_or_jar_blocks_before_action(self):
        candidate = self.prepare()
        self.write(self.exe, b'changed executable')
        self.error('VENDOR_MISMATCH', self.before, candidate)

    def test_wrong_installed_bytes_owner_mode_or_loaded_context_blocks(self):
        candidate = self.prepare()
        self.install_fixture(candidate)
        self.write(candidate['destination'], b'different')
        self.error('INSTALLED_MISMATCH', self.installed, candidate)
        self.write(candidate['destination'], candidate['expected_utf8'].encode(), 0o666)
        self.error('PATH_UNSAFE', self.installed, candidate)
        self.write(candidate['destination'], candidate['expected_utf8'].encode())
        for raw in (b'', f'{self.exe} (enforce)\n'.encode(), (f'{self.exe} (unconfined)\n' * 2).encode()):
            self.write(profile.INVENTORY, raw)
            self.error('LOADED_MISMATCH', self.installed, candidate)

    def test_active_context_exact_name_mode_and_legacy_interface(self):
        path = '/proc/123/attr/apparmor/current'
        self.write(path, f'{self.exe} (unconfined)\n'.encode())
        result = profile.verify_context(123, self.exe, filesystem_root=self.root)
        self.assertEqual(result['status'], 'CONTEXT_VERIFIED')
        self.assertEqual(result['interface'], 'APPARMOR_CURRENT')
        for raw in (b'unconfined\n', f'{self.exe} (enforce)\n'.encode(),
                    f'{self.exe}-other (unconfined)\n'.encode(), b'stacked//profile (unconfined)\n'):
            self.write(path, raw)
            self.error('CONTEXT_MISMATCH', profile.verify_context, 123, self.exe, filesystem_root=self.root)
        self.local(path).unlink()
        self.write('/proc/123/attr/current', f'{self.exe} (unconfined)'.encode())
        self.assertEqual(profile.verify_context(123, self.exe, filesystem_root=self.root)['interface'], 'LSM_CURRENT')

    def test_context_permission_error_never_falls_back(self):
        original = profile._Observation.read
        def denied(obs, path, **kwargs):
            if str(path).endswith('/apparmor/current'):
                raise PermissionError('hidden')
            self.fail('legacy read must not happen after denial')
        with patch.object(profile._Observation, 'read', denied):
            self.error('CONTEXT_UNKNOWN', profile.verify_context, 123, self.exe, filesystem_root=self.root)

    def test_public_record_and_exception_are_hash_enum_only(self):
        candidate = self.prepare()
        public = profile.public_evidence(candidate)
        serialized = json.dumps(public)
        for hidden in (str(self.exe), candidate['destination'], 'include <', 'other-policy', 'PATH', 'Copyright'):
            self.assertNotIn(hidden, serialized)
        for key, value in public.items():
            if key.endswith('sha256'):
                self.assertRegex(value, '^[0-9a-f]{64}$')
        candidate['vendor'][0]['sha256'] = 'raw private text'
        candidate['seal'] = profile._sha(profile._canonical({k: v for k, v in candidate.items() if k != 'seal'}))
        self.error('CANDIDATE_INVALID', profile.public_evidence, candidate)


class ParserContextTests(Fixture):
    def test_exact_trusted_usrmerge_aliases_preserve_normal_provider_route(self):
        self.local('/bin').symlink_to('usr/bin')
        self.local('/sbin').symlink_to('usr/sbin')
        self.env['PATH'] = '/sbin:/bin:/usr/sbin:/usr/bin'
        self.write('/usr/bin/xterm', b'fixture terminal', 0o755)
        self.write('/usr/bin/sudo', b'fixture sudo', 0o755)
        with patch.object(profile.os, 'geteuid', return_value=1000):
            candidate = self.prepare()
            self.assertEqual(candidate['parser']['route'], 'TERMINAL_SUDO')
            self.assertEqual(candidate['parser']['expected_helpers']['TERMINAL']['path'], '/usr/bin/xterm')
            self.assertEqual(candidate['parser']['expected_helpers']['SUDO']['path'], '/usr/bin/sudo')
            aliases = [r for r in candidate['parser']['files'] if r.get('role') == 'DISTRO_PATH_ALIAS']
            self.assertEqual([(r['path'], r['target']) for r in aliases], [('/sbin', 'usr/sbin'), ('/bin', 'usr/bin')])
            self.assertEqual(self.before(candidate, runner=self.runner)['status'], 'PREINSTALL_VERIFIED')

    def test_distro_alias_target_replacement_or_removal_invalidates_snapshot(self):
        self.local('/bin').symlink_to('usr/bin')
        self.env['PATH'] = '/bin:/usr/sbin:/usr/bin'
        candidate = self.prepare()
        self.local('/bin').unlink()
        self.local('/bin').symlink_to('/usr/bin')
        self.assertEqual(self.error('PATH_UNSAFE', self.before, candidate).step, 'PROVIDER_ROUTE')
        self.local('/bin').unlink()
        self.local('/bin').mkdir()
        self.assertEqual(self.error('FILE_CHANGED', self.before, candidate).step, 'PROVIDER_ROUTE')

    def test_alias_exception_does_not_allow_chains_other_links_or_writable_target(self):
        self.env['PATH'] = '/bin:/usr/sbin:/usr/bin'
        alias = self.local('/bin')
        for target in ('/usr/bin', 'usr/../usr/bin', 'usr/sbin', 'missing', 'sbin'):
            alias.symlink_to(target)
            self.error('PATH_UNSAFE', self.prepare)
            alias.unlink()
        alias.symlink_to('usr/bin')
        self.local('/usr/bin').chmod(0o777)
        self.error('PATH_UNSAFE', self.prepare)
        self.local('/usr/bin').chmod(0o755)
        self.local('/usr/bin').rename(self.local('/usr/real-bin'))
        self.local('/usr/bin').symlink_to('real-bin')
        self.error('PARSER_CONTEXT_UNKNOWN', self.prepare)

    def test_nonallowlisted_provider_path_symlink_is_still_rejected(self):
        self.local('/tools').symlink_to('usr/bin')
        self.env['PATH'] = '/tools:/usr/sbin:/usr/bin'
        self.error('PARSER_CONTEXT_UNKNOWN', self.prepare)

    def test_trusted_directory_alias_does_not_allow_a_linked_provider_executable(self):
        self.local('/bin').symlink_to('usr/bin')
        self.env['PATH'] = '/bin:/usr/sbin:/usr/bin'
        self.write('/usr/bin/xterm', b'fixture terminal', 0o755)
        self.write('/usr/bin/real-sudo', b'fixture sudo', 0o4755)
        self.local('/usr/bin/sudo').symlink_to('real-sudo')
        with patch.object(profile.os, 'geteuid', return_value=1000):
            self.error('PATH_UNSAFE', self.prepare)
        self.assertEqual(self.calls, [])

    def test_parser_failures_keep_distinct_fixed_observation_steps(self):
        replacements = (
            ('PACKAGE_IDENTITY', '/usr/bin/dpkg-query', None, b'unknown package private text'),
            ('PARSER_VERSION', '/usr/sbin/apparmor_parser', ['--version'], b'unknown version private text'),
            ('PARSER_CONFIG', '/usr/sbin/apparmor_parser', ['--print-config-file', '--version'], b'/private/config\n'),
            ('CACHE_LOCATION', '/usr/sbin/apparmor_parser', ['--print-cache-dir'], b'/private/cache\n'),
        )
        for step, executable, arguments, raw in replacements:
            def changed(command, **kwargs):
                result = self.runner(command, **kwargs)
                if command[0] == executable and (arguments is None or command[1:] == arguments):
                    result.stdout = raw
                return result
            with self.subTest(step=step):
                error = self.error('PARSER_CONTEXT_UNKNOWN', self.prepare, runner=changed)
                self.assertEqual(error.step, step)
                self.assertNotIn('private', repr(error))

    def test_nested_filesystem_failures_retain_the_observed_role(self):
        self.write(profile.INVENTORY, b'malformed private inventory')
        self.assertEqual(self.error('INVENTORY_UNKNOWN', self.prepare).step, 'KERNEL_INVENTORY')
        self.write(profile.INVENTORY, b'')
        self.write('/etc/apparmor.d/tunables/global', b'include <unknown/file>\n')
        self.assertEqual(self.error('INCLUDE_UNKNOWN', self.prepare).step, 'INCLUDE_CLOSURE')
        self.write('/etc/apparmor.d/tunables/global', b'# valid\n')
        candidate = self.prepare()
        self.write(profile.CONFIG, b'# modified\n')
        self.assertEqual(self.error('FILE_CHANGED', self.before, candidate).step, 'PARSER_CONFIG')

    def test_installed_bytes_and_active_context_have_separate_steps(self):
        candidate = self.prepare()
        self.install_fixture(candidate)
        self.write(candidate['destination'], b'wrong private contents')
        self.assertEqual(self.error('INSTALLED_MISMATCH', self.installed, candidate).step, 'INSTALLED_BYTES')
        self.write('/proc/123/attr/apparmor/current', b'unconfined\n')
        error = self.error('CONTEXT_MISMATCH', profile.verify_context, 123, self.exe, filesystem_root=self.root)
        self.assertEqual(error.step, 'ACTIVE_CONTEXT')

    def test_only_read_only_supervised_helper_commands_are_used(self):
        candidate = self.prepare()
        commands = [call[0] for call in self.calls]
        self.assertEqual(len(commands), 4)
        self.assertTrue(all('-r' not in c and '--replace' not in c for c in commands))
        self.assertTrue(all(0 < call[1]['timeout'] <= 5 for call in self.calls))
        self.assertTrue(all(call[1]['stdout'] == subprocess.PIPE and call[1]['stderr'] == subprocess.DEVNULL for call in self.calls))
        self.assertEqual(candidate['parser']['roots'], ['/etc/apparmor.d'])
        self.assertEqual(candidate['parser']['defaults'], 'UBUNTU_APPARMOR_4_0_1')
        self.assertEqual(candidate['parser']['expected_helpers'], {})

    def test_exact_sudo_identity_handshake_precedes_only_the_managed_probe(self):
        self.write('/usr/bin/xterm', b'fixture terminal', 0o755)
        self.write('/usr/bin/sudo', b'fixture sudo', 0o4755)
        fixture = self
        class ManagedRunner:
            def __init__(self):
                self.expected = None
                self.events = []
            def expect_sudo_probe(self, helper):
                fixture.assertIsNone(self.expected)
                self.expected = copy.deepcopy(helper)
                self.events.append(('EXPECT_SUDO', copy.deepcopy(helper)))
                # The handshake receives a copy; it cannot mutate the private
                # candidate's verified on-disk identity through this argument.
                helper['identity'][0] = -1
            def run(self, command, **kwargs):
                if command == ['/usr/bin/sudo', '-n', '-l']:
                    fixture.assertIsNotNone(self.expected)
                    fixture.assertEqual(self.expected['path'], command[0])
                    self.expected = None
                    self.events.append(('SUDO_PROBE', command))
                else:
                    fixture.assertIsNone(self.expected)
                return fixture.runner(command, **kwargs)
        managed = ManagedRunner()
        with patch.object(profile.os, 'geteuid', return_value=1000):
            candidate = self.prepare(runner=managed.run)
        helpers = candidate['parser']['expected_helpers']
        self.assertEqual(set(helpers), {'TERMINAL', 'SUDO'})
        for helper in helpers.values():
            self.assertEqual(set(helper), {'path', 'identity', 'sha256'})
            self.assertEqual(len(helper['identity']), 7)
            self.assertTrue(all(type(value) is int for value in helper['identity']))
            self.assertNotEqual(helper['identity'][0], -1)
            record = next(r for r in candidate['parser']['files'] if r.get('path') == helper['path'])
            self.assertEqual(helper, record)
        self.assertEqual([event[0] for event in managed.events], ['EXPECT_SUDO', 'SUDO_PROBE'])
        self.assertEqual(managed.events[0][1], helpers['SUDO'])

    def test_rejected_sudo_expectation_stops_before_probe_and_keeps_fixed_diagnostic(self):
        self.write('/usr/bin/xterm', b'fixture terminal', 0o755)
        self.write('/usr/bin/sudo', b'fixture sudo', 0o4755)
        fixture = self
        class DeniedRunner:
            def expect_sudo_probe(self, helper):
                raise RuntimeError('private supervisor diagnostic')
            def run(self, command, **kwargs):
                fixture.fail('denied expectation must not launch the probe')
        with patch.object(profile.os, 'geteuid', return_value=1000):
            error = self.error('PARSER_CONTEXT_UNKNOWN', self.prepare, runner=DeniedRunner().run)
        self.assertEqual(error.step, 'PROVIDER_ROUTE')

    def test_no_runner_or_unknown_package_cannot_assert_context(self):
        self.error('PARSER_CONTEXT_UNKNOWN', self.prepare, runner=None)
        def changed(command, **kwargs):
            result = self.runner(command, **kwargs)
            if command[0] == '/usr/bin/dpkg-query':
                result.stdout = b'install ok installed\t9.9-custom\tamd64\n'
            return result
        self.error('PARSER_CONTEXT_UNKNOWN', self.prepare, runner=changed)

    def test_changed_config_unknown_option_and_cache_collision_block(self):
        for raw in (b'namespace other\n', b'override-policy-abi /other\n', b'ofile /private\n',
                    b'Include /unknown\n', b'Complain\n'):
            self.write(profile.CONFIG, raw)
            self.error('PARSER_CONTEXT_UNKNOWN', self.prepare)
        self.write(profile.CONFIG, b'# standard\n')
        candidate = self.prepare()
        self.write('/var/cache/apparmor/synthetic-feature/idea-null', b'prior compiled policy')
        self.error('PROFILE_COLLISION', self.before, candidate)
        self.error('PROFILE_COLLISION', self.prepare)

    def test_mode_forcing_and_disabling_entries_are_not_ignored(self):
        candidate = self.prepare()
        for directory in ('disable', 'force-complain'):
            path = self.write(f'/etc/apparmor.d/{directory}/idea-null', b'fixture')
            self.error('PARSER_CONTEXT_UNKNOWN', self.prepare)
            self.error('FILE_CHANGED', self.before, candidate)
            path.unlink()

    def test_explicit_include_search_order_is_observed_and_preserved(self):
        self.local('/usr/share/apparmor').mkdir(parents=True)
        self.write(profile.CONFIG, b'Include=/usr/share/apparmor\nskip-read-cache\n')
        self.write('/usr/share/apparmor/abi/4.0', b'policy { versions { v8 { yes } } }\n')
        self.write('/usr/share/apparmor/tunables/global', b'# first search root\n')
        self.local('/usr/share/apparmor/local').mkdir()
        candidate = self.prepare()
        self.assertEqual(candidate['parser']['roots'], ['/usr/share/apparmor', '/etc/apparmor.d'])
        self.assertEqual(candidate['includes'][0]['path'], '/usr/share/apparmor/abi/4.0')

    def test_earlier_provider_is_not_hidden_or_bypassed(self):
        self.write('/usr/bin/pkexec', b'fixture', 0o755)
        with patch.object(profile.os, 'geteuid', return_value=1000):
            self.error('PARSER_CONTEXT_UNKNOWN', self.prepare)
        self.assertEqual(self.calls, [])

    def test_normal_terminal_sudo_needs_fresh_managed_recheck(self):
        self.write('/usr/bin/xterm', b'fixture', 0o755)
        self.write('/usr/bin/sudo', b'fixture', 0o755)
        with patch.object(profile.os, 'geteuid', return_value=1000):
            candidate = self.prepare()
            self.assertEqual(candidate['parser']['route'], 'TERMINAL_SUDO')
            self.error('PARSER_CONTEXT_UNKNOWN', self.before, candidate)
            self.assertEqual(self.before(candidate, runner=self.runner)['status'], 'PREINSTALL_VERIFIED')

    def test_companion_requires_fresh_private_actual_observation_receipt(self):
        self.local('/control').mkdir(mode=0o700)
        receipt = Path('/control/provider-observation.json')
        candidate = self.prepare()
        self.before(candidate, runner=self.runner, receipt_path=receipt)
        count = len(self.calls)
        result = profile.recheck_snapshot(candidate, self.exe, receipt_path=receipt,
                                          env=self.env, filesystem_root=self.root)
        self.assertEqual(result['status'], 'PREINSTALL_VERIFIED')
        self.assertEqual(len(self.calls), count)
        issued = json.loads(self.local(receipt).read_bytes())['issued_ns']
        with patch.object(profile.time, 'monotonic_ns', return_value=issued + 5_000_000_001):
            self.error('PARSER_CONTEXT_UNKNOWN', profile.recheck_snapshot, candidate, self.exe,
                       receipt_path=receipt, env=self.env, filesystem_root=self.root)
        self.local(receipt).chmod(0o644)
        self.error('PARSER_CONTEXT_UNKNOWN', profile.recheck_snapshot, candidate, self.exe,
                   receipt_path=receipt, env=self.env, filesystem_root=self.root)

    def test_companion_still_rechecks_includes_after_provider_receipt(self):
        self.local('/control').mkdir(mode=0o700)
        receipt = Path('/control/provider-observation.json')
        candidate = self.prepare()
        self.before(candidate, runner=self.runner, receipt_path=receipt)
        self.write('/etc/apparmor.d/tunables/global', b'# changed after primary check\n')
        self.error('FILE_CHANGED', profile.recheck_snapshot, candidate, self.exe,
                   receipt_path=receipt, env=self.env, filesystem_root=self.root)


class TrustFixtures(unittest.TestCase):
    def test_distro_alias_must_be_a_root_owned_link(self):
        profile._trust_distro_alias(SimpleNamespace(st_uid=0, st_mode=stat.S_IFLNK | 0o777))
        for uid, mode in ((1000, stat.S_IFLNK | 0o777), (0, stat.S_IFREG | 0o644), (0, stat.S_IFDIR | 0o755)):
            with self.assertRaises(profile.ProfileError):
                profile._trust_distro_alias(SimpleNamespace(st_uid=uid, st_mode=mode))

    def test_root_owned_nonwritable_regular_and_directory_required(self):
        for directory in (False, True):
            filetype = stat.S_IFDIR if directory else stat.S_IFREG
            for uid, permissions in ((1000, 0o755), (0, 0o777), (0, 0o775), (0, 0o757)):
                with self.subTest(directory=directory, uid=uid, permissions=permissions):
                    with self.assertRaises(profile.ProfileError):
                        profile._trust(SimpleNamespace(st_uid=uid, st_mode=filetype | permissions), directory)
            profile._trust(SimpleNamespace(st_uid=0, st_mode=filetype | 0o755), directory)
        with self.assertRaises(profile.ProfileError):
            profile._trust(SimpleNamespace(st_uid=0, st_mode=stat.S_IFLNK | 0o777))


class DiagnosticEnumFixtures(unittest.TestCase):
    def test_error_diagnostics_accept_only_exact_enum_scalars(self):
        for step in profile.STEPS:
            error = profile.ProfileError('FILE_UNKNOWN', step=step)
            self.assertEqual(error.step, step)
            self.assertEqual(error.args, ('FILE_UNKNOWN',))
        class StringSubclass(str):
            pass
        for payload in ({'step': 'PARSER_CONFIG', 'secret': '/private'},
                        ['PARSER_CONFIG'], ('PARSER_CONFIG',), True, 7, None,
                        'PARSER_CONFIG\n/private', StringSubclass('PARSER_CONFIG')):
            error = profile.ProfileError(payload, step=payload)
            self.assertEqual(error.code, 'FILE_UNKNOWN')
            self.assertEqual(error.step, 'UNSPECIFIED')
            self.assertEqual(error.args, ('FILE_UNKNOWN',))

    def test_nested_observation_retains_inner_enum_and_resets_context(self):
        with self.assertRaises(profile.ProfileError) as caught:
            with profile._step('PROVIDER_ROUTE'):
                with profile._step('PARSER_CONFIG'):
                    profile._fail('PARSER_CONTEXT_UNKNOWN')
        self.assertEqual(caught.exception.step, 'PARSER_CONFIG')
        self.assertEqual(profile._CURRENT_STEP.get(), 'UNSPECIFIED')
        with self.assertRaises(profile.ProfileError) as caught:
            with profile._step({'step': 'PARSER_CONFIG', 'secret': '/private'}):
                profile._fail('FILE_UNKNOWN')
        self.assertEqual(caught.exception.step, 'UNSPECIFIED')


if __name__ == '__main__':
    unittest.main()
